version: '3'
services:
  app:
    build: .
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
      - PORT=4200
      - DATABASE_URL=postgres://postgres:root@db:5432/mydb
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: expenses_tracker
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
